"""Live Strategy Monitor — Statistical Process Control.

Answers the question: "Is the strategy still working, or has it degraded?"

Uses sequential analysis to detect when live performance has diverged
from the backtested distribution, triggering automatic alerts or halts.

Key concepts:
1. CUSUM (Cumulative Sum) control chart — detects mean shifts
2. Drawdown control — triggers on unexpected drawdown depth/duration
3. Trade-level monitoring — tracks win rate and payoff ratio drift
"""
from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

import numpy as np

logger = logging.getLogger(__name__)


@dataclass
class TradeRecord:
    """A single completed trade for monitoring."""

    trade_id: int
    symbol: str
    entry_date: str
    exit_date: str
    pnl: float
    pnl_pct: float
    entry_signal_score: float = 0.0
    regime_at_entry: str = ""
    exit_reason: str = ""


@dataclass
class MonitorAlert:
    """An alert generated by the monitor."""

    timestamp: str
    severity: str        # "INFO", "WARNING", "CRITICAL", "HALT"
    category: str        # "drawdown", "win_rate", "sharpe", "cusum"
    message: str
    metric_value: float
    threshold: float
    recommendation: str


@dataclass
class KillCriteria:
    """Pre-committed kill criteria. Define these BEFORE trading.

    These are non-negotiable. If any criterion is hit, trading stops
    immediately regardless of narrative explanations.
    """

    max_drawdown_pct: float = 20.0          # halt if drawdown exceeds this
    max_consecutive_losers: int = 8          # halt after N consecutive losses
    min_rolling_win_rate: float = 0.35       # halt if 30-trade win rate drops below
    max_drawdown_duration_days: int = 45     # halt if in drawdown for N days
    min_monthly_sharpe_3m: float = -0.5      # halt if 3-month rolling Sharpe < this
    cusum_threshold: float = 5.0             # CUSUM drift detection threshold
    min_trades_for_win_rate_kill: int = 30   # don't kill on win rate until N trades
    min_trades_for_cusum_kill: int = 20      # don't kill on CUSUM until N trades

    def to_dict(self) -> dict[str, Any]:
        """Serialize kill criteria to a plain dictionary.

        Returns:
            Dict mapping criterion names to their threshold values.
        """
        return {
            "max_drawdown_pct": self.max_drawdown_pct,
            "max_consecutive_losers": self.max_consecutive_losers,
            "min_rolling_win_rate": self.min_rolling_win_rate,
            "max_drawdown_duration_days": self.max_drawdown_duration_days,
            "min_monthly_sharpe_3m": self.min_monthly_sharpe_3m,
            "cusum_threshold": self.cusum_threshold,
            "min_trades_for_win_rate_kill": self.min_trades_for_win_rate_kill,
            "min_trades_for_cusum_kill": self.min_trades_for_cusum_kill,
        }


class LiveMonitor:
    """Monitors live strategy performance against backtested expectations.

    Uses Statistical Process Control (SPC) techniques to detect when
    the live return distribution has shifted away from the backtested
    expectation. Three complementary detectors run in parallel:

    - Drawdown control: stops trading after exceptional peak-to-trough loss
    - Win-rate control: stops trading when recent trade success collapses
    - CUSUM: detects gradual mean-shift in P&L before it becomes obvious

    Args:
        expected_sharpe: Sharpe ratio from backtest (annualized).
        expected_win_rate: Win rate from backtest (fraction in [0, 1]).
        expected_avg_pnl: Average trade P&L from backtest (dollars).
        kill_criteria: Pre-committed stopping rules. Defaults to conservative
            institutional-grade thresholds.
        log_dir: Directory to persist trade log and alerts as JSON.
    """

    def __init__(
        self,
        expected_sharpe: float = 0.7,
        expected_win_rate: float = 0.60,
        expected_avg_pnl: float = 50.0,
        kill_criteria: KillCriteria | None = None,
        log_dir: str = "logs/monitor",
    ) -> None:
        self.expected_sharpe = expected_sharpe
        self.expected_win_rate = expected_win_rate
        self.expected_avg_pnl = expected_avg_pnl
        self.kill_criteria = kill_criteria or KillCriteria()
        self._log_dir = Path(log_dir)
        self._log_dir.mkdir(parents=True, exist_ok=True)

        self._trades: list[TradeRecord] = []
        self._daily_pnl: list[float] = []
        self._alerts: list[MonitorAlert] = []
        self._peak_equity: float = 0.0
        self._current_equity: float = 0.0
        self._drawdown_start: str | None = None
        self._cusum_pos: float = 0.0
        self._cusum_neg: float = 0.0
        self._is_halted: bool = False
        self._halt_reason: str = ""

    # ------------------------------------------------------------------
    # Public properties
    # ------------------------------------------------------------------

    @property
    def is_halted(self) -> bool:
        """True if the monitor has triggered a halt."""
        return self._is_halted

    @property
    def halt_reason(self) -> str:
        """Human-readable reason for the most recent halt."""
        return self._halt_reason

    @property
    def trade_count(self) -> int:
        """Number of trades recorded so far."""
        return len(self._trades)

    @property
    def all_alerts(self) -> list[MonitorAlert]:
        """All alerts generated since monitor creation (read-only copy)."""
        return list(self._alerts)

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def record_trade(self, trade: TradeRecord) -> list[MonitorAlert]:
        """Record a completed trade and run all trade-level checks.

        Runs drawdown, consecutive-loser, win-rate, and CUSUM checks
        after each trade. Any triggered alerts are returned immediately
        so callers can act on them synchronously.

        Args:
            trade: Completed trade with realised P&L.

        Returns:
            List of MonitorAlert objects generated by this trade.
        """
        self._trades.append(trade)
        self._current_equity += trade.pnl
        self._peak_equity = max(self._peak_equity, self._current_equity)

        alerts: list[MonitorAlert] = []
        alerts.extend(self._check_drawdown())
        alerts.extend(self._check_consecutive_losers())
        alerts.extend(self._check_win_rate())
        alerts.extend(self._check_cusum(trade.pnl))

        self._alerts.extend(alerts)
        self._persist_state()

        return alerts

    def record_daily_pnl(self, pnl: float) -> list[MonitorAlert]:
        """Record daily portfolio P&L for rolling Sharpe monitoring.

        Should be called once per trading day with the net realised +
        unrealised change in portfolio value. Triggers a rolling Sharpe
        check every 21 trading days (approximately monthly).

        Args:
            pnl: Net P&L for the day in dollars.

        Returns:
            List of MonitorAlert objects generated, if any.
        """
        self._daily_pnl.append(pnl)
        self._current_equity += pnl
        self._peak_equity = max(self._peak_equity, self._current_equity)

        alerts: list[MonitorAlert] = []

        # Check rolling Sharpe every 21 days (monthly cadence)
        if len(self._daily_pnl) >= 63 and len(self._daily_pnl) % 21 == 0:
            alerts.extend(self._check_rolling_sharpe())

        alerts.extend(self._check_drawdown())
        self._alerts.extend(alerts)
        return alerts

    # ------------------------------------------------------------------
    # Private checkers
    # ------------------------------------------------------------------

    def _check_drawdown(self) -> list[MonitorAlert]:
        """Check if current drawdown from peak exceeds kill criteria.

        Returns:
            HALT alert if max drawdown breached; WARNING at 70% of limit.
        """
        alerts: list[MonitorAlert] = []
        if self._peak_equity <= 0:
            return alerts

        dd_pct = (
            (self._peak_equity - self._current_equity) / self._peak_equity * 100
        )

        if dd_pct > self.kill_criteria.max_drawdown_pct:
            self._halt(
                f"Drawdown {dd_pct:.1f}% exceeds limit "
                f"{self.kill_criteria.max_drawdown_pct}%"
            )
            alerts.append(
                MonitorAlert(
                    timestamp=datetime.now().isoformat(),
                    severity="HALT",
                    category="drawdown",
                    message=f"MAX DRAWDOWN EXCEEDED: {dd_pct:.1f}%",
                    metric_value=dd_pct,
                    threshold=self.kill_criteria.max_drawdown_pct,
                    recommendation="STOP TRADING IMMEDIATELY. Review strategy.",
                )
            )
        elif dd_pct > self.kill_criteria.max_drawdown_pct * 0.7:
            alerts.append(
                MonitorAlert(
                    timestamp=datetime.now().isoformat(),
                    severity="WARNING",
                    category="drawdown",
                    message=(
                        f"Drawdown warning: {dd_pct:.1f}% "
                        f"(limit: {self.kill_criteria.max_drawdown_pct}%)"
                    ),
                    metric_value=dd_pct,
                    threshold=self.kill_criteria.max_drawdown_pct,
                    recommendation="Reduce position sizes. Review recent trades.",
                )
            )

        return alerts

    def _check_consecutive_losers(self) -> list[MonitorAlert]:
        """Check current consecutive losing streak against kill criteria.

        Returns:
            HALT alert if streak meets or exceeds limit; WARNING at limit minus 2.
        """
        alerts: list[MonitorAlert] = []
        if len(self._trades) < 3:
            return alerts

        streak = 0
        for trade in reversed(self._trades):
            if trade.pnl < 0:
                streak += 1
            else:
                break

        limit = self.kill_criteria.max_consecutive_losers

        if streak >= limit:
            self._halt(
                f"{streak} consecutive losers exceeds limit {limit}"
            )
            alerts.append(
                MonitorAlert(
                    timestamp=datetime.now().isoformat(),
                    severity="HALT",
                    category="win_rate",
                    message=f"CONSECUTIVE LOSERS: {streak}",
                    metric_value=float(streak),
                    threshold=float(limit),
                    recommendation="STOP TRADING. Strategy may have degraded.",
                )
            )
        elif streak >= limit - 2:
            alerts.append(
                MonitorAlert(
                    timestamp=datetime.now().isoformat(),
                    severity="WARNING",
                    category="win_rate",
                    message=f"Losing streak: {streak} consecutive losers",
                    metric_value=float(streak),
                    threshold=float(limit),
                    recommendation="Review recent trades for pattern changes.",
                )
            )

        return alerts

    def _check_win_rate(self) -> list[MonitorAlert]:
        """Check 30-trade rolling win rate against kill criteria.

        Kill is suppressed until at least ``kill_criteria.min_trades_for_win_rate_kill``
        trades have been recorded to avoid false positives from small samples.

        Returns:
            HALT alert if rolling win rate drops below the minimum threshold.
        """
        alerts: list[MonitorAlert] = []
        window = 30
        if len(self._trades) < window:
            return alerts
        if len(self._trades) < self.kill_criteria.min_trades_for_win_rate_kill:
            return alerts

        recent = self._trades[-window:]
        win_rate = sum(1 for t in recent if t.pnl > 0) / len(recent)

        if win_rate < self.kill_criteria.min_rolling_win_rate:
            self._halt(
                f"Win rate {win_rate:.1%} below minimum "
                f"{self.kill_criteria.min_rolling_win_rate:.1%}"
            )
            alerts.append(
                MonitorAlert(
                    timestamp=datetime.now().isoformat(),
                    severity="HALT",
                    category="win_rate",
                    message=(
                        f"WIN RATE COLLAPSED: {win_rate:.1%} "
                        f"over last {window} trades"
                    ),
                    metric_value=win_rate,
                    threshold=self.kill_criteria.min_rolling_win_rate,
                    recommendation="STOP TRADING. Signal may no longer work.",
                )
            )

        return alerts

    def _check_cusum(self, trade_pnl: float) -> list[MonitorAlert]:
        """CUSUM (Cumulative Sum) control chart for mean-shift detection.

        **What it tracks:** Per-trade P&L deviation from ``expected_avg_pnl``.
        Each trade contributes a standardised score ``z = (pnl - expected) / std_est``
        where ``std_est`` is estimated as 50% of the absolute expected P&L.
        The negative CUSUM accumulates downward deviations; it resets toward 0
        whenever a trade beats expectation.

        **Detection delay:** Depends on the allowance parameter (currently 0.5 sigma)
        and ``kill_criteria.cusum_threshold``. With threshold=5 and allowance=0.5,
        a strategy delivering 1 sigma below expectation per trade will typically
        trigger after roughly 10–15 trades. Larger thresholds mean longer delay
        but fewer false alarms.

        **Tuning:**
        - Lower threshold → faster detection, more false alarms.
        - Higher threshold → slower detection, fewer false alarms.
        - Increase allowance (0.5 → 1.0) to ignore small mean shifts and only
          respond to large sustained deterioration.

        Alerts are suppressed until ``kill_criteria.min_trades_for_cusum_kill``
        trades have been recorded to avoid early false positives.

        Args:
            trade_pnl: P&L of the most recently completed trade.

        Returns:
            CRITICAL alert if negative CUSUM exceeds threshold and the minimum
            trade count has been reached.
        """
        alerts: list[MonitorAlert] = []

        # Standardize: how far is this trade from expected?
        std_est = (
            abs(self.expected_avg_pnl) * 0.5
            if abs(self.expected_avg_pnl) > 0
            else 1.0
        )
        deviation = trade_pnl - self.expected_avg_pnl
        z = deviation / std_est

        # CUSUM update — tracking negative drift (allowance = 0.5 sigma)
        self._cusum_neg = min(0.0, self._cusum_neg + z + 0.5)
        self._cusum_pos = max(0.0, self._cusum_pos + z - 0.5)

        # Suppress alerts until minimum trade count is reached
        if len(self._trades) < self.kill_criteria.min_trades_for_cusum_kill:
            return alerts

        if abs(self._cusum_neg) > self.kill_criteria.cusum_threshold:
            alerts.append(
                MonitorAlert(
                    timestamp=datetime.now().isoformat(),
                    severity="CRITICAL",
                    category="cusum",
                    message=(
                        f"CUSUM drift detected: strategy mean has shifted negative "
                        f"(CUSUM={self._cusum_neg:.2f})"
                    ),
                    metric_value=float(self._cusum_neg),
                    threshold=self.kill_criteria.cusum_threshold,
                    recommendation=(
                        "Strategy performance has structurally degraded. "
                        "Review and potentially halt."
                    ),
                )
            )

        return alerts

    def _check_rolling_sharpe(self) -> list[MonitorAlert]:
        """Check 3-month (63-day) rolling Sharpe ratio.

        A Sharpe below the kill threshold suggests the strategy has stopped
        generating alpha on a sustained basis.

        Returns:
            HALT alert if 3-month rolling Sharpe drops below threshold.
        """
        alerts: list[MonitorAlert] = []
        if len(self._daily_pnl) < 63:
            return alerts

        recent = np.array(self._daily_pnl[-63:])
        std = float(np.std(recent, ddof=1))
        sharpe_3m = (
            float(np.mean(recent)) / std * np.sqrt(252) if std > 1e-10 else 0.0
        )

        if sharpe_3m < self.kill_criteria.min_monthly_sharpe_3m:
            self._halt(
                f"3-month Sharpe {sharpe_3m:.2f} below minimum "
                f"{self.kill_criteria.min_monthly_sharpe_3m:.2f}"
            )
            alerts.append(
                MonitorAlert(
                    timestamp=datetime.now().isoformat(),
                    severity="HALT",
                    category="sharpe",
                    message=f"ROLLING SHARPE COLLAPSE: {sharpe_3m:.2f}",
                    metric_value=float(sharpe_3m),
                    threshold=self.kill_criteria.min_monthly_sharpe_3m,
                    recommendation=(
                        "STOP TRADING. Strategy no longer generating alpha."
                    ),
                )
            )

        return alerts

    # ------------------------------------------------------------------
    # Class-method constructors
    # ------------------------------------------------------------------

    @classmethod
    def from_backtest_distribution(
        cls,
        backtest_trade_pnls: list[float],
        confidence_level: float = 0.99,
        n_simulations: int = 10000,
    ) -> LiveMonitor:
        """Create a monitor with kill thresholds calibrated from backtest MC.

        Instead of arbitrary thresholds, this uses the backtest trade distribution
        to set kills at the ``confidence_level`` percentile of what "strategy still
        working" looks like. If live performance is worse than 99% of simulated
        paths, the strategy has likely degraded.

        Args:
            backtest_trade_pnls: List of trade P&Ls from backtest.
            confidence_level: Kill threshold percentile (0.99 = 99th percentile).
            n_simulations: Number of MC paths to simulate.

        Returns:
            A new LiveMonitor instance with MC-calibrated KillCriteria.
        """
        pnls = np.array(backtest_trade_pnls)
        n_trades = len(pnls)
        rng = np.random.default_rng(42)

        max_drawdowns: list[float] = []
        max_consecutive_losers_list: list[int] = []
        min_win_rates: list[float] = []

        for _ in range(n_simulations):
            sim_trades = rng.choice(pnls, size=n_trades, replace=True)

            # Max drawdown
            cumulative = np.cumsum(sim_trades)
            peak = np.maximum.accumulate(cumulative)
            dd = peak - cumulative
            max_dd_pct = float(np.max(dd) / np.max(peak) * 100) if np.max(peak) > 0 else 0.0
            max_drawdowns.append(max_dd_pct)

            # Max consecutive losers
            max_streak = 0
            streak = 0
            for p in sim_trades:
                if p < 0:
                    streak += 1
                    max_streak = max(max_streak, streak)
                else:
                    streak = 0
            max_consecutive_losers_list.append(max_streak)

            # Worst 30-trade win rate
            if len(sim_trades) >= 30:
                worst_wr = float(
                    min(
                        np.mean(sim_trades[i : i + 30] > 0)
                        for i in range(0, len(sim_trades) - 29)
                    )
                )
            else:
                worst_wr = float(np.mean(sim_trades > 0))
            min_win_rates.append(worst_wr)

        kill = KillCriteria(
            max_drawdown_pct=float(
                np.percentile(max_drawdowns, confidence_level * 100)
            ),
            max_consecutive_losers=int(
                np.percentile(max_consecutive_losers_list, confidence_level * 100)
            ),
            min_rolling_win_rate=float(
                np.percentile(min_win_rates, (1 - confidence_level) * 100)
            ),
        )

        avg_pnl = float(np.mean(pnls))
        win_rate = float(np.mean(pnls > 0))
        std_pnl = float(np.std(pnls))
        sharpe_est = (
            avg_pnl / std_pnl * np.sqrt(252 / 5) if std_pnl > 0 else 0.0
        )

        logger.info(
            "MC-calibrated kill criteria (%.0f%% confidence): "
            "max_dd=%.1f%%, max_consec=%d, min_wr=%.1f%%",
            confidence_level * 100,
            kill.max_drawdown_pct,
            kill.max_consecutive_losers,
            kill.min_rolling_win_rate * 100,
        )

        return cls(
            expected_sharpe=float(sharpe_est),
            expected_win_rate=win_rate,
            expected_avg_pnl=avg_pnl,
            kill_criteria=kill,
        )

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _halt(self, reason: str) -> None:
        """Mark the strategy as halted with a reason string.

        Idempotent: calling again after already halted has no effect.
        """
        if not self._is_halted:
            self._is_halted = True
            self._halt_reason = reason
            logger.critical("STRATEGY HALTED: %s", reason)

    def _persist_state(self) -> None:
        """Persist a lightweight JSON snapshot of monitor state to disk."""
        state: dict[str, Any] = {
            "trades": len(self._trades),
            "current_equity": self._current_equity,
            "peak_equity": self._peak_equity,
            "is_halted": self._is_halted,
            "halt_reason": self._halt_reason,
            "cusum_neg": self._cusum_neg,
            "cusum_pos": self._cusum_pos,
            "alerts": len(self._alerts),
            "last_updated": datetime.now().isoformat(),
        }
        state_file = self._log_dir / "monitor_state.json"
        state_file.write_text(json.dumps(state, indent=2))

    # ------------------------------------------------------------------
    # Reporting
    # ------------------------------------------------------------------

    def status_report(self) -> str:
        """Generate a concise human-readable status report.

        Returns:
            Multi-line string suitable for logging or display.
        """
        n = len(self._trades)
        if n == 0:
            return "No trades recorded yet."

        wins = sum(1 for t in self._trades if t.pnl > 0)
        total_pnl = sum(t.pnl for t in self._trades)
        win_rate = wins / n

        dd_pct = 0.0
        if self._peak_equity > 0:
            dd_pct = (
                (self._peak_equity - self._current_equity)
                / self._peak_equity
                * 100
            )

        critical_count = sum(
            1
            for a in self._alerts[-10:]
            if a.severity in ("CRITICAL", "HALT")
        )

        lines = [
            f"Strategy Monitor Status "
            f"({datetime.now().strftime('%Y-%m-%d %H:%M')})",
            f"  Trades: {n} | Win rate: {win_rate:.1%} "
            f"(expected: {self.expected_win_rate:.1%})",
            f"  Total P&L: ${total_pnl:,.2f} | "
            f"Current drawdown: {dd_pct:.1f}%",
            f"  CUSUM: {self._cusum_neg:.2f} "
            f"(threshold: {self.kill_criteria.cusum_threshold})",
            f"  Status: "
            f"{'HALTED — ' + self._halt_reason if self._is_halted else 'ACTIVE'}",
            f"  Recent alerts: {critical_count} critical",
        ]
        return "\n".join(lines)
